### ISSUE TITLE
Nested folder include directories are not included in the C++ Properties

### ISSUE THREAD

**Issue by kjeremy** [ajshort/vscode-ros#1]
The root ROS include directories ie:
> "/home/jkolb/Development/mrak_new/devel/include",
> "/opt/ros/indigo/include",
>  "/usr/include"

Are included in the C++ settings.  However individual include directories for projects are not.

**Comment by ajshort** [comment]
Unfortunately I'm not aware of an easy way to gather this information. I guess a good enough approach might be to just scan all workspace packages for a directory named `include`.

**Comment by JamesGiller** [comment]
I have noticed recently that VS Code offers to add the correct subdirectory to one of the search paths in the C++ properties file, if you click the little light bulb icon next to a green-underlined #include. 

It has also offered to add paths to system folders containing standard library headers etc.

So the issue would now be just to make it more convenient for the user to add paths to the properties file, without having to click on the green-underlines.
