### ISSUE TITLE
Holistic vscode setup for ROS

### ISSUE THREAD

**Issue by beetleskin** [ajshort/vscode-ros#12]
Thanks a lot for the effort with the plugin! I just installed it, but wonder how I can transform my VSCode into a full-blown IDE for ROS C++ and Python development. Specifically I'm looking for:

* correct and useful code completion (python and c++)
* catkin build/partial build tasks
* c++ code analysis (unused vars, function, includes, ..)
* c++ and python linter
* llvm/gdb debugging
* git integration that can deal with the catkin workspace setup (each package in src/ is a git repo, managed by wstool
* .. whatever clion can do :)

I've been playing a lot with the common cmake and c++ plugings, but failed to configure everything to be really useful. Some issues I encounter:
* Intellisense can't find includes or wrong ones (my own common_types.h was assotiated with pcl's common_types.h
* code completion shows me *any* symbol there is, but not the members of an object I'm comleting on
* code completion and resolving dependencies takes quite some time and is apparently not caching, so every time I close and open a c++ file, I have to wait a minute or so until I can start working.

---

PS: I know there is [RoboWare](http://www.roboware.me/), but this attempt fails at so many core code develop features, but concentrates on rather fancy high-level stuff like GUI and rosmaster inspection.

**Comment by ajshort** [comment]
Issues to do with code completion/intellisense are out of the control of this extension - it just provides the include paths to the standard C++/Python extensions. In terms of a full-blown IDE setup, have you tried just using CLion? It supports CMake-based projects out of the box.

I'm going to close this off as I don't think there's anything specifically actionable. Thanks for the feedback though.

**Comment by beetleskin** [comment]
Alright, fair enoug. I assumed, as the writer of a ROS plugin vor vscode, you'd have it configured to be a complete IDE for ROS development :) 
Anyhow, do I need to do something special to make the include paths work with the [default C++ plugin](https://marketplace.visualstudio.com/items?itemName=ms-vscode.cpptools)? As stated above, some includes are not resolved, others are wrong in my workspace.
