### ISSUE TITLE
Commands not found and no syntax highlighting

### ISSUE THREAD

**Issue by JamesGiller** [ajshort/vscode-ros#2]
I am running the following version of VS Code on Ubuntu 16.04
![1.15.1](https://user-images.githubusercontent.com/1397123/29507195-128c20b0-868a-11e7-843f-9e6a26cd5299.png)

I installed the extension from "Extensions" in the Activity Bar, and was prompted to also install the dependency Msg Language Support. To try it out, I created a new workspace according to [catkin_tools quickstart](http://catkin-tools.readthedocs.io/en/latest/quick_start.html) (I should say that the `catkin init` command does not create a link to the top-level CMakeLists.txt file like catkin_init_workspace does).

Everything seemed to install fine, but when I started to try the extension by running Start Core command in my opened workspace an error appeared saying "command 'ros.startCore' not found". Similar errors appear for all other commands, so it seems like none of the commands were actually installed.

Opening a CMakeLists.txt file also shows no syntax highlighting.

**Comment by ajshort** [comment]
I haven't tried the extension with catkin tools - can you try using `catkin_init_workspace`? I'm guessing a `.catkin_workspace` file wasn't created, which is what the extension relies on.

You'll need a separate extension for CMake syntax highlighting.

**Comment by JamesGiller** [comment]
You're right that `.catkin_workspace` file wasn't created, but it wasn't created by either `catkin init` or `catkin_init_workspace`, at least for me. Should it be automatically generated?

Creating the empty file myself made everything work fine it seems.

**Comment by JamesGiller** [comment]
Yes, I'm using Kinetic. Some ROS packages were upgraded just this morning.

**Comment by JamesGiller** [comment]
Sorry, I must have missed something these past years... I have always used catkin_init_workspace or catkin init, but it seems that those commands have not been necessary for a long time. After creating ~/my_workspace/src just execute the `catkin_make` command in the my_workspace directory and the `.catkin_workspace` file will be created automatically.

**Comment by ajshort** [comment]
Glad you found the issue. Ideally the initial build wouldn't be required, but I've added a note to the README for now at least.
