### ISSUE TITLE
ros melodic: catkin: command not found

### ISSUE THREAD

**Issue by roman-tub** [ajshort/vscode-ros#25]
When I run catkin_make from terminal everything works fine, but when I use the catkin release or debug tasks I get  `bash: catkin: command not found`

ros gets sourced in my .bashrc. 

An suggestions?

**Comment by BryceStevenWilley** [comment]
Looks like the extension is trying to use [catkin tools](https://catkin-tools.readthedocs.io/en/latest/), not `catkin_make`. Try [installing](https://catkin-tools.readthedocs.io/en/latest/installing.html) those.

**Comment by roman-tub** [comment]
Thanks!
