### ISSUE TITLE
Roslaunch configuration doesn't work

### ISSUE THREAD

**Issue by Renha** [ajshort/vscode-ros#3]
I'm using VS Code Insider and trying to use configuration:
```
{
  "configurations": [
    {
      "command": "roslaunch",
      "debugSettings": "${command:debugSettings}",
      "name": "launcher_name.launch",
      "package": "pkg_name",
      "type": "ros",
      "target": "launcher_name.launch",
      "request": "launch"
    }
  ],
  "version": "0.1.0"
}
```

and when I hit f5 it says:

> Usage: roslaunch [options] [package] <filename> [arg_name:=value...]
>       roslaunch [options] <filename> [<filename>...] [arg_name:=value...]
>If <filename> is a single dash ('-'), launch XML is read from standard input.
> roslaunch: error: The following input files do not exist: undefined

**Comment by Renha** [comment]
oh, it just need
```
      "args": [
        
      ]
```

**Comment by ahmadi86** [comment]
I am having the same problem. I changed "configurations" to "args". But now, it tries to configure ros settings again instead of running the code.

**Comment by ajshort** [comment]
Thanks @Renha, I will fix this issue.

@ahmadi86 breakpoints are currently not supported.

**Comment by ajshort** [comment]
dbd3af26034b806801992acffe2bc2bc98fa4145

**Comment by larissadj** [comment]
H,i have the same problem , but i don't know where i can do the modifications of this configuration(how is the name of this ordner of Roslaunch)?Thanks for any suggest.

**Comment by gencom** [comment]
{
            "request": "launch",
            "type": "ros",
            "command": "roslaunch",
            "name": "config name",
            "package": "rospackagename",
            "target": "run_scenario.launch",
            "debugSettings": "debugSettings",
            "args": ["scenario:=scn1"]
        }

**Comment by stdmkmehp** [comment]
> ```
> {
>         "request": "launch",
>         "type": "ros",
>         "command": "roslaunch",
>         "name": "config name",
>         "package": "rospackagename",
>         "target": "run_scenario.launch",
>         "debugSettings": "debugSettings",
>         "args": ["scenario:=scn1"]
>     }
> ```
> same iusse cant launch with args. and debugger ingoring launch answer file. running by manual selecting roslaunch and package name. project working but ignoring launch.json file

Same issue. VScode ignores launch.json.
Have you got a solution?
