### ISSUE TITLE
catkin tools support

### ISSUE THREAD

**Issue by raghavkhanna** [ajshort/vscode-ros#4]
Hi,

Thanks for this neat extension. Are there any plans to support `catkin tools`? Or may be you could point me to what changes would be needed and I could try to add support and send a PR?

Cheers,
Raghav

**Comment by ajshort** [comment]
Not at the moment - I haven't really used catkin tools so don't know much about it. What are the main missing features you would want to gain by using catkin tools?

Most of the catkin related code is in `catkin.ts` and `catkin-task-provider.ts`.

**Comment by raghavkhanna** [comment]
Thanks, it's just a part of our current build workflow, and afaik one cannot use both of them interchangeably. Here's a nice overview of the comparison with catkin_make

http://catkin-tools.readthedocs.io/en/latest/migration.html

**Comment by dc217863** [comment]
is there any update to this?

**Comment by ajshort** [comment]
This isn't something I'm actively working on - contributions would definitely be welcome though. I envision it would just be a configuration option.
